"""modifidied order_id

Revision ID: 611aedadfea6
Revises: 78cbf20c2361
Create Date: 2025-04-12 15:10:13.573138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611aedadfea6'
down_revision = '78cbf20c2361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
