"""adding image to the Product

Revision ID: 78cbf20c2361
Revises: 
Create Date: 2025-04-10 20:14:37.017431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cbf20c2361'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_img'), ['img'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_img'))
        batch_op.drop_column('img')

    # ### end Alembic commands ###
